#[derive(Debug, Clone, Copy, PartialEq)]
pub enum StatusHTTP {
    Continue,
    SwitchingProtocols,
    Processing,
    EarlyHints,
    OK,
    Created,
    Accepted,
    NonAuthoritativeInformation,
    NoContent,
    ResetContent,
    PartialContent,
    MultiStatus,
    AlreadyReported,
    IMUsed,
    MultipleChoices,
    MovedPermanently,
    Found,
    SeeOther,
    NotModified,
    UseProxy,
    TemporaryRedirect,
    PermanentRedirect,
    BadRequest,
    Unauthorized,
    PaymentRequired,
    Forbidden,
    NotFound,
    MethodNotAllowed,
    NotAcceptable,
    ProxyAuthenticationRequired,
    RequestTimeout,
    Conflict,
    Gone,
    LengthRequired,
    PreconditionFailed,
    ContentTooLarge,
    URITooLong,
    UnsupportedMediaType,
    RangeNotSatisfiable,
    ExpectationFailed,
    MisdirectedRequest,
    UnprocessableContent,
    Locked,
    FailedDependency,
    TooEarly,
    UpgradeRequired,
    PreconditionRequired,
    TooManyRequests,
    RequestHeaderFieldsTooLarge,
    UnavailableForLegalReasons,
    InternalServerError,
    NotImplemented,
    BadGateway,
    ServiceUnavailable,
    GatewayTimeout,
    HTTPVersionNotSupported,
    VariantAlsoNegotiates,
    InsufficientStorage,
    LoopDetected,
    NotExtended,
    NetworkAuthenticationRequired,
}

impl StatusHTTP {
    pub fn as_bytes(self) -> &'static [u8] {
        self.as_str().as_bytes()
    }

    pub fn as_str(self) -> &'static str {
        match self {
            StatusHTTP::Continue => "100 Continue",
            StatusHTTP::SwitchingProtocols => "101 Switching Protocols",
            StatusHTTP::Processing => "102 Processing",
            StatusHTTP::EarlyHints => "103 Early Hints",
            StatusHTTP::OK => "200 OK",
            StatusHTTP::Created => "201 Created",
            StatusHTTP::Accepted => "202 Accepted",
            StatusHTTP::NonAuthoritativeInformation => "203 Non-Authoritative Information",
            StatusHTTP::NoContent => "204 No Content",
            StatusHTTP::ResetContent => "205 Reset Content",
            StatusHTTP::PartialContent => "206 Partial Content",
            StatusHTTP::MultiStatus => "207 Multi-Status",
            StatusHTTP::AlreadyReported => "208 Already Reported",
            StatusHTTP::IMUsed => "226 IM Used",
            StatusHTTP::MultipleChoices => "300 Multiple Choices",
            StatusHTTP::MovedPermanently => "301 Moved Permanently",
            StatusHTTP::Found => "302 Found",
            StatusHTTP::SeeOther => "303 See Other",
            StatusHTTP::NotModified => "304 Not Modified",
            StatusHTTP::UseProxy => "305 Use Proxy",
            StatusHTTP::TemporaryRedirect => "307 Temporary Redirect",
            StatusHTTP::PermanentRedirect => "308 Permanent Redirect",
            StatusHTTP::BadRequest => "400 Bad Request",
            StatusHTTP::Unauthorized => "401 Unauthorized",
            StatusHTTP::PaymentRequired => "402 Payment Required",
            StatusHTTP::Forbidden => "403 Forbidden",
            StatusHTTP::NotFound => "404 Not Found",
            StatusHTTP::MethodNotAllowed => "405 Method Not Allowed",
            StatusHTTP::NotAcceptable => "406 Not Acceptable",
            StatusHTTP::ProxyAuthenticationRequired => "407 Proxy Authentication Required",
            StatusHTTP::RequestTimeout => "408 Request Timeout",
            StatusHTTP::Conflict => "409 Conflict",
            StatusHTTP::Gone => "410 Gone",
            StatusHTTP::LengthRequired => "411 Length Required",
            StatusHTTP::PreconditionFailed => "412 Precondition Failed",
            StatusHTTP::ContentTooLarge => "413 Content Too Large",
            StatusHTTP::URITooLong => "414 URI Too Long",
            StatusHTTP::UnsupportedMediaType => "415 Unsupported Media Type",
            StatusHTTP::RangeNotSatisfiable => "416 Range Not Satisfiable",
            StatusHTTP::ExpectationFailed => "417 Expectation Failed",
            StatusHTTP::MisdirectedRequest => "421 Misdirected Request",
            StatusHTTP::UnprocessableContent => "422 Unprocessable Content",
            StatusHTTP::Locked => "423 Locked",
            StatusHTTP::FailedDependency => "424 Failed Dependency",
            StatusHTTP::TooEarly => "425 Too Early",
            StatusHTTP::UpgradeRequired => "426 Upgrade Required",
            StatusHTTP::PreconditionRequired => "428 Precondition Required",
            StatusHTTP::TooManyRequests => "429 Too Many Requests",
            StatusHTTP::RequestHeaderFieldsTooLarge => "431 Request Header Fields Too Large",
            StatusHTTP::UnavailableForLegalReasons => "451 Unavailable For Legal Reasons",
            StatusHTTP::InternalServerError => "500 Internal Server Error",
            StatusHTTP::NotImplemented => "501 Not Implemented",
            StatusHTTP::BadGateway => "502 Bad Gateway",
            StatusHTTP::ServiceUnavailable => "503 Service Unavailable",
            StatusHTTP::GatewayTimeout => "504 Gateway Timeout",
            StatusHTTP::HTTPVersionNotSupported => "505 HTTP Version Not Supported",
            StatusHTTP::VariantAlsoNegotiates => "506 Variant Also Negotiates",
            StatusHTTP::InsufficientStorage => "507 Insufficient Storage",
            StatusHTTP::LoopDetected => "508 Loop Detected",
            StatusHTTP::NotExtended => "510 Not Extended",
            StatusHTTP::NetworkAuthenticationRequired => "511 Network Authentication Required",
        }
    }
}
